tasks:
  build-push-run:
    image: gcr.io/kaniko-project/executor
    args:
      - --dockerfile
      - ./run/Dockerfile
      - --context
      - $(GIT_CLONE_DIR)/run
      - --destination
      - index.docker.io/sailci/run:$(GIT_SHORT_SHA)
    mounts:
      - /root/.docker/config.json: DOCKER_AUTH
    when: \/heads\/master$
  build-push-clone-github:
    image: gcr.io/kaniko-project/executor
    args:
      - --dockerfile
      - ./clone-github/Dockerfile
      - --context
      - $(GIT_CLONE_DIR)/clone-github
      - --destination
      - index.docker.io/sailci/clone-github:$(GIT_SHORT_SHA)
    mounts:
      - /root/.docker/config.json: DOCKER_AUTH
    when: \/heads\/master$